#!/bin/bash

function main {

    if [[ -z ${ROOTSYS} ]]; then
        echo "ROOTSYS not found, setup ROOT first"
        return
    fi

    if [ ! $(which hdf-tuple-from-root 2>/dev/null) ]; then
        echo "Cannot find path to hdf-tuple-from-root executable, did you call source setup_h5.sh?"
        return 
    fi

    echo "INFO: Converting files to HDF5"
    list_of_files=${@}
    file_array=( $list_of_files )
    #echo "list of files = ${list_of_files}"
    #for f in $file_array ; do
    for findex in ${!file_array[@]}; do
        idxstr=$((findex+1))
        f="${file_array[$findex]}"
        echo "[${idxstr}/${#file_array[@]}] ${f}"
        is_root=".root"
        if [[ ${f} == *${is_root}* ]]; then
            oname=$(basename ${f})
            nf=$(echo "${oname}" | sed 's/root/h5/')
            hdf-tuple-from-root ${f} ${nf} #1>/dev/null # remove warnings about missing vars
        else
            echo " > WARNING Skipping file ${f}"
        fi
    done
}

main $*
